---
## Remove any specified package using user supplied VARIABLES ##

# Created by Karan Chhabra 07/03/2021 #
# This playbook will:
# 1. Uninstall packages
# 2. Take the package name from user prompt
# 3. Verify the package is uninstalled
# 4. Print package verification status

- name: Playbook to remove packages
  hosts: all
  gather_facts: true
  tasks:

    - name: Removing "{{ PACKAGE_NAME }}"   # Removing supplied package
      yum:
        name: "{{ PACKAGE_NAME }}"
        state: absent

    - name: Verify "{{ PACKAGE_NAME }}" uninstallation           # Check status for package uninstallation
      shell: 'rpmquery "{{ PACKAGE_NAME }}"'
      ignore_errors: True
      register: package_status

    - name: Print package status             # Print package status
      debug:
        msg: "{{ package_status.stdout_lines }}"
