---
## Create User Playbook ##

# Created by Karan Chhabra 27/2/21
# This playbook will do the following on all of the ansible controlled hosts:
# 1. Create a new user
# 2. Add home directory
# 3. Add shell for the user
# 4. Add the created user to a group

- name: Playbook to create a user with attributes
  hosts: all
  tasks:
    - name: Create a user named thor
      user:
        name: thor
        password: <ADD GENERATED PASSWORD BY redhat-ansible/generate_password/generate_random_pass.sh SCRIPT FROM THIS REPOSITORY>
        home: /home/thor
        shell: /bin/bash
        groups: avengers